# Generated by Django 5.2.10 on 2026-02-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('BAIXA', 'Baixa'), ('MITJANA', 'Mitjana'), ('ALTA', 'Alta')], default='BAIXA', max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
