name: DevSecOps Pipeline


on:


push:
branches: [ "main", "master" ]


jobs :
auditoria_seguretat:
runs-on: ubuntu-latest


steps :
- name: Descarregar el codi
uses: actions/checkout@v4


- name: Configurar Python
uses: actions/setup-python@v5
with:
python-version: '3.11'
name: Instal.lar dependencies
run: |
python -m pip install -- upgrade pip
pip install -r requirements.txt


- name: Instal.lar Firefox i Geckodriver
run:
sudo apt-get update
sudo apt-get install -y firefox
sudo apt-get install -y firefox-geckodriver


- name: Executar Tests de Seguretat
env:
SECRET_KEY: ${{ secrets. SECRET_KEY }}
MOZ_HEADLESS: 1
run: |
python manage.py test
